# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_files/lizhibin/FIR_Simple/FIR_Simple.srcs/sources_1/ip/fir250_45/fir250_45.xci
# IP: The module: 'fir250_45' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_files/lizhibin/FIR_Simple/FIR_Simple.gen/sources_1/ip/fir250_45/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir250_45'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_files/lizhibin/FIR_Simple/FIR_Simple.gen/sources_1/ip/fir250_45/fir250_45_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir250_45'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/vivado_files/lizhibin/FIR_Simple/FIR_Simple.srcs/sources_1/ip/fir250_45/fir250_45.xci
# IP: The module: 'fir250_45' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_files/lizhibin/FIR_Simple/FIR_Simple.gen/sources_1/ip/fir250_45/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir250_45'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/vivado_files/lizhibin/FIR_Simple/FIR_Simple.gen/sources_1/ip/fir250_45/fir250_45_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir250_45'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
